language: ruby
rvm:
    - 2.2
before_script:
    - gem install awesome_bot
script:
    - awesome_bot README.md --white-list CONTRIBUTING.md,amzn.com,carnivore.it,domaintools.com,cymru.com,clean-mx.de,woodmann.com,andrototal.org,crdf.fr,zscaler.com,fireeye,threatcrowd
